apiVersion: v1
kind: Service
metadata:
    name: redis-slave-svc
    labels: 
      name: redis-slave
spec: 
    ports:
    - port: 6379
      targetPort: 6379    
    selector:
      name: redis-slave
---      
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
    name: redis-slave
    labels:
        name: redis-slave
spec:
    replicas: 1
    selector:
        matchLabels:
            name: redis-slave
    template:
        metadata:
            labels: {name: redis-slave}
        spec:
            containers: 
            - name: slave
              image: kubeguide/guestbook-redis-slave
              ports: 
              - containerPort: 6379
              
