apiVersion: v1
kind: Service
metadata:
    name: redis-master-svc
    labels: 
      name: redis-master
spec: 
    ports:
    - port: 6379
      targetPort: 6379    
    selector:
      name: redis-master
---      
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
    name: redis-master
    labels:
        name: redis-master
spec:
    replicas: 1
    selector:
        matchLabels:
            name: redis-master
    template:
        metadata:
            labels: {name: redis-master}
        spec:
            containers: 
            - name: master
              image: kubeguide/redis-master
              ports: 
              - containerPort: 6379
              
