apiVersion: v1
kind: Service
metadata:
    name: frontend
    labels: 
      name: frontend
spec: 
    type: NodePort
    ports:
    - port: 80
      nodePort: 30003    
    selector:
      name: frontend
---      
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
    name: frontend
    labels:
        name: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            name: frontend
    template:
        metadata:
            labels: {name: frontend}
        spec:
            containers: 
            - name: frontend
              image: kubeguide/guestbook-php-frontend
              ports: 
              - containerPort: 80
              
